@startuml "Domain Model Diagram"

object stock {
    + acronym
    + price
}

class StockDescriptor {
    + shares
}

stock "1" .. "1" StockDescriptor : < describes

class TradeController {
    + stocks : StockDescriptor[]
    + buy(s: StockDescriptor)
    + sell(s: StockDescriptor)
}

StockDescriptor "1..*" .. "1" TradeController : < Manages

class DataMonitor {
    + data : DataFrame
    + append(stock : StockDescriptor)
    + update_prices()
}

TradeController "1" .. "1" DataMonitor : < Triggers
StockDescriptor "0..*" .. "1" DataMonitor : < Monitors

class Timer {
    + interval : int
}

Timer "1" .. "1" DataMonitor : > Triggers

class StockTransaction {
    + day_of_year : int
    + year : int
    + buy : bool
}

StockDescriptor "1" .. "0..*" StockTransaction : < Describes a\ntransaction of

StockTransaction "0..*" .. "1" TradeController : < Generates

class DataLogger {
    + data : DataFrame
    + append(trade : StockDescriptor)
    + save(filename : string)
}

DataLogger "1" .. "1" TradeController : < Triggers
DataLogger "1" .. "0..*" StockTransaction : > Documents

@enduml
