@startuml "Domain Model Diagram"

object stock {
    + acronym
    + price
}

class StockDescriptor {
    + shares
}

stock "1" .. "1" StockDescriptor : < describes

class TradeController {
    + stocks : StockDescriptor[]
    + buy(s: StockDescriptor)
    + sell(s: StockDescriptor)
}

StockDescriptor "1..*" .. "1" TradeController : < Manages

object website {
    + name
    + price
}

class WebsiteDescriptor {
    + Day of year
    + Year
}

website "1" .. "1" WebsiteDescriptor : < describes

class WebsiteParser {
    + url : string
    + parse() : WebsiteDescriptor[]
}

WebsiteParser "1" .. "0..*" WebsiteDescriptor : > creates

class WebsiteController {
    + sites : WebsiteParser[]
    + pollWebsites() : WebsiteDescriptor[]
}

WebsiteController "1" .. "1..*" WebsiteParser : > Controls

class DataMonitor {
    + data : DataFrame
    + append(site : WebsiteDescriptor)
}

TradeController "1" .. "1" DataMonitor : < Triggers

WebsiteController "1" .. "1" DataMonitor : > Triggers

class Timer {
    + interval : int
}

Timer "1" .. "1" WebsiteController : > Triggers

class DataLogger {
    + data : DataFrame
    + append(trade : StockDescriptor)
    + save(filename : string)
}

DataLogger "1" .. "1" TradeController : < Triggers

@enduml
